# Generated by Django 3.2.4 on 2021-06-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('author_name', models.CharField(max_length=30)),
                ('excerpt', models.TextField(max_length=300)),
                ('description', models.TextField()),
                ('num_lessons', models.PositiveSmallIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='course-picture')),
            ],
        ),
    ]
